# Generated by Django 5.1.5 on 2025-02-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_profile',
        ),
    ]
