# Generated by Django 5.1.4 on 2025-02-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rsvp_system_event_participants_delete_participant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RSVP_system',
        ),
    ]
