# Generated by Django 5.1.5 on 2025-02-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_delete_rsvp_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='task_pictures'),
        ),
    ]
