# Generated by Django 5.1.5 on 2025-02-19 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_img', models.ImageField(blank=True, default='profile_img/default.jpg', upload_to='profile_img')),
                ('phone_number', models.TextField(blank=True)),
            ],
        ),
    ]
